// SPDX-License-Identifier: AGPL-3.0-only OR Commercial

//! Derives `PUBLISHED_GALEON_ENGINE_VERSION` from `crates/engine/Cargo.toml` so
//! the major.minor that scaffolded projects pin against (`galeon-engine = "X.Y"`)
//! cannot drift from the engine package this CLI ships alongside. The generated
//! file is included by `src/templates.rs` via `include!`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let engine_manifest = manifest_dir.join("..").join("engine").join("Cargo.toml");
    let workspace_manifest = manifest_dir.join("..").join("..").join("Cargo.toml");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", engine_manifest.display());
    println!("cargo:rerun-if-changed={}", workspace_manifest.display());

    let version = resolve_engine_package_version(&engine_manifest, &workspace_manifest);
    let (major, minor) = parse_major_minor(&version, &engine_manifest);

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("published_galeon_engine_version.rs");

    let contents = format!(
        "// SPDX-License-Identifier: AGPL-3.0-only OR Commercial\n\
         // GENERATED by crates/galeon-cli/build.rs from crates/engine/Cargo.toml. Do not edit.\n\
         pub(crate) const PUBLISHED_GALEON_ENGINE_VERSION: &str = \"{major}.{minor}\";\n"
    );
    fs::write(&dest, contents).unwrap_or_else(|e| panic!("write {} failed: {e}", dest.display()));
}

fn resolve_engine_package_version(engine_manifest: &Path, workspace_manifest: &Path) -> String {
    let engine_text = fs::read_to_string(engine_manifest)
        .unwrap_or_else(|e| panic!("read {} failed: {e}", engine_manifest.display()));
    let engine_toml: toml::Value = toml::from_str(&engine_text)
        .unwrap_or_else(|e| panic!("parse {} failed: {e}", engine_manifest.display()));

    let version = engine_toml
        .get("package")
        .and_then(|p| p.get("version"))
        .unwrap_or_else(|| {
            panic!(
                "{} is missing `[package].version`",
                engine_manifest.display()
            )
        });

    if let Some(literal) = version.as_str() {
        return literal.to_owned();
    }

    let inherits_workspace = version
        .as_table()
        .and_then(|t| t.get("workspace"))
        .and_then(|w| w.as_bool())
        .unwrap_or(false);

    if !inherits_workspace {
        panic!(
            "unsupported `[package].version` form in {}: expected a string literal \
             or `version.workspace = true`",
            engine_manifest.display()
        );
    }

    let workspace_text = fs::read_to_string(workspace_manifest)
        .unwrap_or_else(|e| panic!("read {} failed: {e}", workspace_manifest.display()));
    let workspace_toml: toml::Value = toml::from_str(&workspace_text)
        .unwrap_or_else(|e| panic!("parse {} failed: {e}", workspace_manifest.display()));

    workspace_toml
        .get("workspace")
        .and_then(|w| w.get("package"))
        .and_then(|p| p.get("version"))
        .and_then(|v| v.as_str())
        .map(str::to_owned)
        .unwrap_or_else(|| {
            panic!(
                "{} is missing `[workspace.package].version` (required because {} declares \
                 `version.workspace = true`)",
                workspace_manifest.display(),
                engine_manifest.display(),
            )
        })
}

fn parse_major_minor(version: &str, source: &Path) -> (String, String) {
    let mut parts = version.split('.');
    let major = parts.next().unwrap_or_default();
    let minor = parts.next().unwrap_or_default();
    if major.is_empty() || minor.is_empty() {
        panic!(
            "version `{version}` from {} is missing a major.minor pair",
            source.display()
        );
    }
    if major.parse::<u64>().is_err() || minor.parse::<u64>().is_err() {
        panic!(
            "version `{version}` from {} is not numeric major.minor",
            source.display()
        );
    }
    (major.to_owned(), minor.to_owned())
}
